let $LANG='ja'
set encoding=utf-8
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set title
syntax on
set smartindent
set ignorecase
set showmatch
set number
set smarttab
set backspace=indent,eol,start
